export const allProjects = [
  {
    id: 1,
    name: 'Expanding Cards',
    description: 'Project of expanding cards with images.',
    img: '/project01/capa.png',
    url: '/expanding-cards',
  },
  {
    id: 2,
    name: 'Progress Steps',
    description: 'Project of progress steps with button prev and next.',
    img: '/project02/capa.png',
    url: '/progress-steps',
  },
  {
    id: 3,
    name: 'Blurry Loading',
    description: 'Project of loading with blurred image according to loading percentage.',
    img: '/project03/capa.png',
    url: '/blurry-loading',
  },
  {
    id: 4,
    name: 'Scroll Animation',
    description: 'Project of scroll animation basic and button for view more cards of text.',
    img: '/project04/capa.png',
    url: '/scroll-animation',
  },
  {
    id: 5,
    name: 'Form Input Wave',
    description: 'Project of form with inputs wave - effect - validate.',
    img: '/project05/capa.png',
    url: '/form-input-wave',
  },
  {
    id: 6,
    name: 'Sound Board',
    description: 'Project of sound board, click on the button to listen.',
    img: '/project06/capa.png',
    url: '/sound-board',
  },
  {
    id: 7,
    name: 'Random Jokes',
    description: 'Project of random jokes received from an api: https://icanhazdadjoke.com, where every request already arrives a different joke, a favorite option was added where it is possible to save the jokes.',
    img: '/project07/capa.png',
    url: '/random-jokes',
  },
  {
    id: 8,
    name: 'Random Choice Picker',
    description: 'Project of random choice picker, where you write the words and use the comma to separate them and when you press the Enter key, a random choice of one of the words is made.',
    img: '/project08/capa.png',
    url: '/random-choice-picker',
  },
  {
    id: 9,
    name: 'Increment Counter',
    description: 'Project of increment counter for items of emphasis - Facebook - Instagram - YouTube.',
    img: '/project09/capa.png',
    url: '/increment-counter',
  },
  {
    id: 10,
    name: 'Drink Water',
    description: 'Project of track your daily water intake, allowing you to set a personalized water consumption goal.',
    img: '/project10/capa.png',
    url: '/drink-water',
  },
  {
    id: 11,
    name: 'Background Slider',
    description: 'Project of background slider with autoplay and slide loop options.',
    img: '/project11/capa.png',
    url: '/background-slider',
  },
  {
    id: 12,
    name: 'Theme Clock',
    description: 'Clock project with dark and light theme - analogue and digital clock with date.',
    img: '/project12/capa.png',
    url: '/theme-clock',
  },
  {
    id: 13,
    name: 'Button Ripple Effect',
    description: 'Project of button ripple effect - this effect simulates waves propagating from the click point of contact, creating a sense of interactivity and visual feedback for the user.',
    img: '/project13/capa.png',
    url: '/button-ripple-effect',
  },
  {
    id: 14,
    name: 'Kinetic Loader',
    description: 'Project of Kinetic Loader and click ESC remove Loader.',
    img: '/project14/capa.png',
    url: '/kinetic-loader',
  },
  {
    id: 15,
    name: 'Skeleton Loader Card',
    description: 'Project of Skeleton Loader Card. Shows a similar replica of the card while the card has not been loaded.',
    img: '/project15/capa.png',
    url: '/skeleton-loader-card',
  },
  {
    id: 16,
    name: 'Vertical Slider',
    description: 'Project of double vertical slider.',
    img: '/project16/capa.png',
    url: '/vertical-slider',
  },
  {
    id: 17,
    name: 'Toast Notification',
    description: 'Project of toast notification. Information and error messages that are cleared from the screen in 1500ms.',
    img: '/project17/capa.png',
    url: '/toast-notification',
  },
  {
    id: 18,
    name: 'GitHub Profiles',
    description: 'Project of github profiles. Search the username of the person you want to search on github, interface with effects and responsive.',
    img: '/project18/capa.png',
    url: '/github-profiles',
  },
  {
    id: 19,
    name: 'Double Click Heart',
    description: 'Project of double click heart. Heart effect on mouse click position and likes count',
    img: '/project19/capa.png',
    url: '/double-click-heart',
  },
  {
    id: 20,
    name: 'Auto Text Effect',
    description: 'Project of auto text effect. Having a list of sentences, it renders one sentence at a time, with the effect of appearing one word at a time "typing effect".',
    img: '/project20/capa.png',
    url: '/auto-text-effect',
  },
  {
    id: 21,
    name: 'Password Generator',
    description: 'Project of password generator. Custom password generator with choice of lowercase, uppercase, numbers, special characters and the length of the password to be generated.',
    img: '/project21/capa.png',
    url: '/password-generator',
  },
  {
    id: 22,
    name: 'Good, Cheap, Fast',
    description: 'Project of good, cheap, fast. Choose how you want the project.',
    img: '/project22/capa.png',
    url: '/good-cheap-fast',
  },
  {
    id: 23,
    name: 'Notes App',
    description: 'Project of notes app. Notes application where data is stored in the browser, with the option to edit and delete.',
    img: '/project23/capa.png',
    url: '/note-app',
  },
  {
    id: 24,
    name: 'Animated Countdown',
    description: 'Project of animatied countdown. Countdown to start with animation effects.',
    img: '/project24/capa.png',
    url: '/animated-countdown',
  },
  {
    id: 25,
    name: 'Hoverboard',
    description: 'Project of hoverboard. Frame that when hovering the mouse over it takes on a random color and fades out again.',
    img: '/project25/capa.png',
    url: '/hoverboard',
  },
  {
    id: 26,
    name: 'Mobile Tab Navigation',
    description: 'Project of mobile tab navigation. Mobile tab navigation with custom styling.',
    img: '/project26/capa.png',
    url: '/mobile-tab-navigation',
  },
  {
    id: 27,
    name: '3D Boxes Background',
    description: 'Project of 3d boxes background.',
    img: '/project27/capa.png',
    url: '/3d-boxes-background',
  },
  {
    id: 28,
    name: 'Live User Filter',
    description: 'Project of live user filter. User search in the list by name, working with requests as well.',
    img: '/project28/capa.png',
    url: '/live-user-filter',
  },
]