export const allProjects = [
  {
    id: 1,
    name: 'Expanding Cards',
    description: 'Project of expanding cards with images.',
    img: '/project01/capa.png',
    url: '/expanding-cards',
  },
  {
    id: 2,
    name: 'Progress Steps',
    description: 'Project of progress steps with button prev and next.',
    img: '/project02/capa.png',
    url: '/progress-steps',
  },
  {
    id: 3,
    name: 'Blurry Loading',
    description: 'Project of loading with blurred image according to loading percentage.',
    img: '/project03/capa.png',
    url: '/blurry-loading',
  },
  {
    id: 4,
    name: 'Scroll Animation',
    description: 'Project of scroll animation basic and button for view more cards of text.',
    img: '/project04/capa.png',
    url: '/scroll-animation',
  },
  {
    id: 5,
    name: 'Form Input Wave',
    description: 'Project of form with inputs wave - effect - validate.',
    img: '/project05/capa.png',
    url: '/form-input-wave',
  },
  {
    id: 6,
    name: 'Sound Board',
    description: 'Project of sound board, click on the button to listen.',
    img: '/project06/capa.png',
    url: '/sound-board',
  },
  {
    id: 7,
    name: 'Random Jokes',
    description: 'Project of random jokes received from an api: https://icanhazdadjoke.com, where every request already arrives a different joke, a favorite option was added where it is possible to save the jokes.',
    img: '/project07/capa.png',
    url: '/random-jokes',
  },
  {
    id: 8,
    name: 'Random Choice Picker',
    description: 'Project of random choice picker, where you write the words and use the comma to separate them and when you press the Enter key, a random choice of one of the words is made.',
    img: '/project08/capa.png',
    url: '/random-choice-picker',
  },
  {
    id: 9,
    name: 'Increment Counter',
    description: 'Project of increment counter for items of emphasis - Facebook - Instagram - YouTube.',
    img: '/project09/capa.png',
    url: '/increment-counter',
  },
  {
    id: 10,
    name: 'Drink Water',
    description: 'Project of track your daily water intake, allowing you to set a personalized water consumption goal.',
    img: '/project10/capa.png',
    url: '/drink-water',
  },
  {
    id: 11,
    name: 'Background Slider',
    description: 'Project of background slider with autoplay and slide loop options.',
    img: '/project11/capa.png',
    url: '/background-slider',
  },
  {
    id: 12,
    name: 'Theme Clock',
    description: 'Clock project with dark and light theme - analogue and digital clock with date.',
    img: '/project12/capa.png',
    url: '/theme-clock',
  },
  {
    id: 13,
    name: 'Button Ripple Effect',
    description: 'Project of button ripple effect - this effect simulates waves propagating from the click point of contact, creating a sense of interactivity and visual feedback for the user.',
    img: '/project13/capa.png',
    url: '/button-ripple-effect',
  }
]